// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiS99SMQPOoJk4kiDEl6AVJ2p87qmBJVU',
    appId: '1:470833212455:web:d814ad7d3ff771e54ef202',
    messagingSenderId: '470833212455',
    projectId: 'chartapp2024',
    authDomain: 'chartapp2024.firebaseapp.com',
    storageBucket: 'chartapp2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3-DxAEBXd4idTfKOkZmKfhXLuY1O2RF8',
    appId: '1:470833212455:android:d6622c852f8b613e4ef202',
    messagingSenderId: '470833212455',
    projectId: 'chartapp2024',
    storageBucket: 'chartapp2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh19CpZ9hQifxbQ7vMlxvX6IiHUNwmmBU',
    appId: '1:470833212455:ios:e2490ffec2a955c84ef202',
    messagingSenderId: '470833212455',
    projectId: 'chartapp2024',
    storageBucket: 'chartapp2024.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh19CpZ9hQifxbQ7vMlxvX6IiHUNwmmBU',
    appId: '1:470833212455:ios:f9bf1e9e0216b6e94ef202',
    messagingSenderId: '470833212455',
    projectId: 'chartapp2024',
    storageBucket: 'chartapp2024.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
